server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connection-init-sqls: set names utf8mb4
      initial-size: 5
      min-idle: 5
      max-active: 20
    url: jdbc:mysql://xxxxx:3306/xxxxxx?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: username
    password: password
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  #配置文件传输
  servlet:
    multipart:
      enabled: true
      #单个文件的大小
      max-file-size: 20MB
      #总数据的大小
      max-request-size: 20MB
# 分页框架
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
